class Cargoplane:
    def takeoff(self):
        print("Plane is takeoff")
    def fly(self):
        print("Plane is flying")
    def land(self):
        print("Plane is landing")
    def carryg(self):
        print("Plane carry goods")
class Passengerplane:
    def takeoff(self):
        print("Plane is takeoff")
    def fly(self):
        print("Plane is flying")
    def land(self):
        print("Plane is landing")
    def carryp(self):
        print("Plane carry goods")
class Fighterplane:
    def takeoff(self):
        print("Plane is takeoff")
    def fly(self):
        print("Plane is flying")
    def land(self):
        print("Plane is landing")
    def carryw(self):
        print("Plane carry goods")
c=Cargoplane()
p=Passengerplane()
f=Fighterplane()
c.takeoff()
c.fly()
c.land()
c.carryg()
p.takeoff()
p.fly()
p.land()
p.carryp()
f.takeoff()
f.fly()
f.land()
f.carryw()